# Site wide configuration

title:            Tapanila.net
name:             Tapanila.net
locale:           en_US
url:              https://tapanila.net


# Jekyll configuration

permalink:   /:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Teemu Tapanila
  avatar: https://images.ctfassets.net/dife9bku7g06/6aXLdREZzsyFDuD19SGruS/be76952260014995ba6106e0ddaa364a/teemu_465.jpeg?w=465&h=465&q=100&fm=webp
  bio: "CTO of Mallow"
  email: teemu@tapanila.net
  disqus-shortname: tapanilanetblog
  twitter: TapanilaT
  google:
    plus:
    analytics: UA-30022509-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 6D281ABEF9F49AD4A241F6391ADC2422
  github: Tapanila
  stackoverflow: #797074/teemu-tapanila
  linkedin: teemutapanila
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "*.ps1","portableJekyll"]
