# Site wide configuration

title:            Tapanila.net
locale:           en_US
url:              https://tapanila.net


# Jekyll configuration

permalink:   /:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Teemu Tapanila
  avatar: https://res.cloudinary.com/tapanila-net/image/upload/c_scale,h_186,q_80/v1411477391/Teemu%20Tapanila.jpg
  bio: "Microsoft Azure MVP and Windows Phone developer"
  email: teemu@tapanila.net
  disqus-shortname: tapanilanetblog
  twitter: TapanilaT
  facebook: Teemu.Tapanila
  google:
    plus: TeemuTapanila
    analytics: UA-30022509-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: Tapanila
  stackoverflow: https://stackoverflow.com/users/797074/teemu-tapanila
  linkedin: teemutapanila
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "*.ps1"]
